#!/usr/bin/env python3
"""
Generate a small Kolla-Ansible inventory from a node list.

Input format:
ip hostname role

Allowed roles:
- controller
- compute
- storage
- all
"""

from pathlib import Path
import argparse
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--nodes",
        default=str(Path(__file__).resolve().parents[1] / "nodes.example.txt"),
        help="Path to nodes file",
    )
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parents[1] / "multinode-arm.ini"),
        help="Output inventory path",
    )
    parser.add_argument(
        "--ansible-user",
        default="ubuntu",
        help="SSH user for Ansible",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    nodes_file = Path(args.nodes)
    output = Path(args.output)

    if not nodes_file.exists():
        print(f"ERROR: missing nodes file: {nodes_file}", file=sys.stderr)
        return 1

    groups: dict[str, list[tuple[str, str]]] = {
        "control": [],
        "network": [],
        "compute": [],
        "storage": [],
        "monitoring": [],
    }

    for line_no, raw in enumerate(nodes_file.read_text().splitlines(), start=1):
        line = raw.strip()

        if not line or line.startswith("#"):
            continue

        parts = line.split()
        if len(parts) < 3:
            print(f"ERROR: invalid line {line_no}: {raw}", file=sys.stderr)
            return 1

        ip, host, role = parts[:3]

        if role in ("controller", "control"):
            groups["control"].append((host, ip))
            groups["network"].append((host, ip))
            groups["monitoring"].append((host, ip))

        elif role == "compute":
            groups["compute"].append((host, ip))

        elif role == "storage":
            groups["storage"].append((host, ip))

        elif role == "all":
            for hosts in groups.values():
                hosts.append((host, ip))

        else:
            print(f"ERROR: unknown role '{role}' on line {line_no}", file=sys.stderr)
            return 1

    if not groups["control"]:
        print("ERROR: inventory must have at least one controller or all node", file=sys.stderr)
        return 1

    if not groups["compute"]:
        print("WARNING: inventory has no compute nodes", file=sys.stderr)

    inventory = [
        "# Generated by 02_generate_inventory.py",
        "# For ARM OpenStack PoC using Kolla-Ansible",
        "",
    ]

    for group, hosts in groups.items():
        inventory.append(f"[{group}]")
        for host, ip in hosts:
            inventory.append(
                f"{host} ansible_host={ip} "
                f"ansible_user={args.ansible_user} "
                f"ansible_python_interpreter=/usr/bin/python3"
            )
        inventory.append("")

    output.write_text("\n".join(inventory) + "\n")
    print(f"Generated inventory: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
